-- 결제 카드 사용불가 BIN 접두·블랙리스트 (전산설정관리)
-- 운영(ddl-auto: validate) 시 1회 실행. 로컬 H2(dev)는 ddl-auto: update.

CREATE TABLE IF NOT EXISTS tb_hq_pay_card_block_prefix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pg_vendor VARCHAR(32) NOT NULL,
    prefix_digits VARCHAR(8) NOT NULL,
    remark VARCHAR(200),
    active_yn VARCHAR(1) NOT NULL DEFAULT 'Y',
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_pay_card_block_prefix_pg ON tb_hq_pay_card_block_prefix (pg_vendor, active_yn);

CREATE TABLE IF NOT EXISTS tb_hq_pay_card_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pg_vendor VARCHAR(32),
    pan_hash VARCHAR(64) NOT NULL,
    pan_display VARCHAR(24) NOT NULL,
    source VARCHAR(16) NOT NULL DEFAULT 'MANUAL',
    reason VARCHAR(500),
    active_yn VARCHAR(1) NOT NULL DEFAULT 'Y',
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pay_card_blacklist_hash ON tb_hq_pay_card_blacklist (pan_hash);

-- JPAY: 유니온페이 60·81 BIN (62만 허용 — 운영 기본값)
INSERT INTO tb_hq_pay_card_block_prefix (pg_vendor, prefix_digits, remark, active_yn, created_at, updated_at)
SELECT 'JPAY', '60', 'UnionPay BIN 60 — JPAY 미지원', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM tb_hq_pay_card_block_prefix WHERE pg_vendor = 'JPAY' AND prefix_digits = '60');

INSERT INTO tb_hq_pay_card_block_prefix (pg_vendor, prefix_digits, remark, active_yn, created_at, updated_at)
SELECT 'JPAY', '81', 'UnionPay BIN 81 — JPAY 미지원', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM tb_hq_pay_card_block_prefix WHERE pg_vendor = 'JPAY' AND prefix_digits = '81');

-- ChillPay: AMEX 접두 (PG 정책)
INSERT INTO tb_hq_pay_card_block_prefix (pg_vendor, prefix_digits, remark, active_yn, created_at, updated_at)
SELECT 'CHILLPAY', '34', 'American Express — ChillPay 미지원', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM tb_hq_pay_card_block_prefix WHERE pg_vendor = 'CHILLPAY' AND prefix_digits = '34');

INSERT INTO tb_hq_pay_card_block_prefix (pg_vendor, prefix_digits, remark, active_yn, created_at, updated_at)
SELECT 'CHILLPAY', '37', 'American Express — ChillPay 미지원', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM tb_hq_pay_card_block_prefix WHERE pg_vendor = 'CHILLPAY' AND prefix_digits = '37');
