-- 대행수수료설정 (ICOPAY↔PG 계약 해석, pg_cd당 1건)
CREATE TABLE IF NOT EXISTS tb_pg_agency_cost_policy (
    id BIGSERIAL PRIMARY KEY,
    pg_cd VARCHAR(20) NOT NULL,
    per_tx_fee NUMERIC(12, 1) DEFAULT 0,
    cancel_rate NUMERIC(12, 1) DEFAULT 0,
    usage_rate NUMERIC(12, 1) DEFAULT 0,
    fail_fee NUMERIC(12, 1) DEFAULT 0,
    pay_rate NUMERIC(5, 2) DEFAULT 0,
    refund_rate NUMERIC(12, 0) DEFAULT 0,
    void_fee_per_tx NUMERIC(12, 0) DEFAULT 0,
    manual_void_fee_per_tx NUMERIC(12, 0) DEFAULT 0,
    fee_settlement_per_tx NUMERIC(12, 0) DEFAULT 0,
    remittance_transfer_fee NUMERIC(12, 1) DEFAULT 0,
    usdt_transfer_fee_usd NUMERIC(12, 1) DEFAULT 0,
    fee_usdt NUMERIC(12, 2) DEFAULT 0,
    fee_fx NUMERIC(12, 2) DEFAULT 0,
    rolling_pct NUMERIC(5, 2) DEFAULT 0,
    rolling_days INT DEFAULT 0,
    currency_code VARCHAR(16) DEFAULT 'KRW',
    policy_remark TEXT,
    fee_3ds_rate NUMERIC(12, 1) DEFAULT 0,
    chargeback_fee_per_tx NUMERIC(12, 1) DEFAULT 0,
    chargeback_policy_id BIGINT,
    void_settlement_mode VARCHAR(16),
    manual_void_settlement_mode VARCHAR(16),
    refund_settlement_mode VARCHAR(16),
    force_refund_settlement_mode VARCHAR(16),
    extra_fee_1_name VARCHAR(64),
    extra_fee_1_mode VARCHAR(8),
    extra_fee_1_value NUMERIC(15, 4),
    extra_fee_2_name VARCHAR(64),
    extra_fee_2_mode VARCHAR(8),
    extra_fee_2_value NUMERIC(15, 4),
    extra_fee_3_name VARCHAR(64),
    extra_fee_3_mode VARCHAR(8),
    extra_fee_3_value NUMERIC(15, 4),
    extra_fee_4_name VARCHAR(64),
    extra_fee_4_mode VARCHAR(8),
    extra_fee_4_value NUMERIC(15, 4),
    settle_basis VARCHAR(20) NOT NULL DEFAULT 'TRANSACTION',
    settle_schedule_type VARCHAR(8) NOT NULL DEFAULT 'T',
    settle_lag_n INT NOT NULL DEFAULT 1,
    settle_batch_time TIME,
    use_yn VARCHAR(1) NOT NULL DEFAULT 'Y',
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uq_pg_agency_cost_policy_pg_cd UNIQUE (pg_cd)
);

CREATE INDEX IF NOT EXISTS ix_pg_agency_cost_policy_pg_cd ON tb_pg_agency_cost_policy (pg_cd);
