-- 비활성카드 마스킹 등록(6+***+4)·결제 실패 쿨다운·전산설정

ALTER TABLE tb_hq_pay_card_blacklist
    ADD COLUMN IF NOT EXISTS holder_name VARCHAR(100);

ALTER TABLE tb_hq_pay_card_blacklist
    ADD COLUMN IF NOT EXISTS match_mode VARCHAR(16) NOT NULL DEFAULT 'FULL_PAN';

COMMENT ON COLUMN tb_hq_pay_card_blacklist.holder_name IS '카드 구분용 표시명(매칭 제외)';
COMMENT ON COLUMN tb_hq_pay_card_blacklist.match_mode IS 'FULL_PAN=전체 해시, MASK_6_4=앞6+***+뒤4 패턴';

CREATE TABLE IF NOT EXISTS tb_pay_card_fail_cooldown (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pg_vendor       VARCHAR(32)  NOT NULL,
    pan_hash        VARCHAR(64)  NOT NULL,
    pan_mask_key    VARCHAR(24),
    fail_count      INTEGER      NOT NULL DEFAULT 0,
    blocked_until   TIMESTAMP,
    last_fail_at    TIMESTAMP,
    last_outcome_code VARCHAR(32),
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pay_card_fail_cooldown_pg_hash
    ON tb_pay_card_fail_cooldown (pg_vendor, pan_hash);

ALTER TABLE pg_trnsctn
    ADD COLUMN IF NOT EXISTS card_pan_hash VARCHAR(64);

COMMENT ON COLUMN pg_trnsctn.card_pan_hash IS '결제 시도 카드 SHA-256(쿨다운·실패 집계용, 평문 미저장)';

ALTER TABLE tb_hq_ledger_sys_settings
    ADD COLUMN IF NOT EXISTS card_fail_cooldown_enabled_yn VARCHAR(1) NOT NULL DEFAULT 'Y';

ALTER TABLE tb_hq_ledger_sys_settings
    ADD COLUMN IF NOT EXISTS card_fail_cooldown_tier1_min INTEGER NOT NULL DEFAULT 5;

ALTER TABLE tb_hq_ledger_sys_settings
    ADD COLUMN IF NOT EXISTS card_fail_cooldown_tier2_min INTEGER NOT NULL DEFAULT 10;

ALTER TABLE tb_hq_ledger_sys_settings
    ADD COLUMN IF NOT EXISTS card_fail_cooldown_tier3_min INTEGER NOT NULL DEFAULT 60;
