-- 본사설정: PG 노티(CALLBACK/RESULT 등) → 전산 화면·그리드 필드 매핑 정의 (JSON)
CREATE TABLE IF NOT EXISTS tb_hq_notify_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_json CLOB,
    updated_at TIMESTAMP
);
