-- 총본사 → 본사(REGIONAL) 단위 VIEW SETTING 허용 컬럼 상한
CREATE TABLE IF NOT EXISTS tb_org_view_column_allowance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regional_org_code VARCHAR(50) NOT NULL,
    page_url VARCHAR(200) NOT NULL,
    allowed_keys_json TEXT NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT uk_org_view_col_allow UNIQUE (regional_org_code, page_url)
);
