-- 전산설정: PG별 사용불가 카드 브랜드 (VISA/MASTER/JCB/UNION/DINERS/AMEX)

CREATE TABLE IF NOT EXISTS tb_hq_pay_card_block_brand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pg_vendor VARCHAR(32) NOT NULL,
    brand_code VARCHAR(16) NOT NULL,
    remark VARCHAR(200),
    active_yn VARCHAR(1) NOT NULL DEFAULT 'Y',
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_pay_card_block_brand_pg
    ON tb_hq_pay_card_block_brand (pg_vendor, active_yn);

CREATE INDEX IF NOT EXISTS ix_pay_card_block_brand_pg_code
    ON tb_hq_pay_card_block_brand (pg_vendor, brand_code);

-- 기존 BIN 접두와 동일 정책 시드 (ChillPay AMEX)
INSERT INTO tb_hq_pay_card_block_brand (pg_vendor, brand_code, remark, active_yn, created_at, updated_at)
SELECT 'CHILLPAY', 'AMEX', 'American Express — ChillPay 미지원', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM tb_hq_pay_card_block_brand WHERE pg_vendor = 'CHILLPAY' AND brand_code = 'AMEX'
);
